/** 坐席管理：独立维护云呼叫坐席、停用恢复和技能配置。 */
(function(){
  'use strict'; const ui=PlatformUI,esc=ui.escape; let view='agents';
  const filters={agents:{keyword:'',status:'全部状态'},skills:{keyword:'',status:'全部状态'},sync:{keyword:'',status:'全部状态'}};
  const pages={agents:1,skills:1,sync:1};const pageSize=8;
  function scoped(rows){return AppState.scoped(rows||[]);}
  function tenantName(id){return CloudCallRuntime.tenant(id)?.name||id;}
  function agentByIdentity(id){return CloudCallData.agents.find(x=>x.contactCenterIdentityId===id);}
  function friendlyReason(value){if(!value)return '—';if(value.includes('LoginName'))return '账号信息已存在，请检查原有坐席账号';return value.split('；')[0].replaceAll('CreateUser','创建坐席');}
  function filterPanel(key,label){const current=filters[key];return `<div class="filter-panel"><label class="field grow"><span>${label}</span><input id="${key}Keyword" value="${esc(current.keyword)}" placeholder="输入姓名或业务系统"></label><label class="field"><span>状态</span><select id="${key}Status"><option>全部状态</option>${['已启用','已删除','停用中','已停用','成功','失败','核查中','已生效'].map(value=>`<option ${current.status===value?'selected':''}>${value}</option>`).join('')}</select></label><div class="filter-actions"><button class="btn" onclick="window.Pages['agent-center'].resetFilters('${key}')">重置</button><button class="btn btn-primary" onclick="window.Pages['agent-center'].query('${key}')">查询</button></div></div>`;}
  function shell(key,rows,columns,primary,help){const start=(pages[key]-1)*pageSize;return `<div class="management-list-shell">${ui.toolbar(primary,`<button class="btn" onclick="window.Pages['agent-center'].refresh('${key}')">刷新</button>${ui.help(help)}`)}${ui.table(columns,rows.slice(start,start+pageSize),{emptyText:'没有符合条件的数据',rowOffset:start})}${ui.pagination(rows.length,pages[key],pageSize,`window.Pages['agent-center'].setPage.bind(null,'${key}')`)}</div>`;}
  function renderAgents(){const current=filters.agents,keyword=current.keyword.toLowerCase();const rows=scoped(CloudCallData.agents).filter(row=>(!keyword||`${row.userName} ${CloudCallData.businessSystems.find(x=>x.businessSystemId===row.businessSystemId)?.name} ${row.mobile}`.toLowerCase().includes(keyword))&&(current.status==='全部状态'||row.lifecycleStatus===current.status)).map(row=>({...row,skills:CloudCallData.agentSkills.filter(item=>item.identityId===row.contactCenterIdentityId).length}));return `<section class="platform-page agent-page" data-anno-page="agent-maintenance" data-anno-label="云呼叫坐席维护" data-anno-kind="region" data-anno-fields="FLD-017,FLD-018,FLD-019,FLD-020,FLD-021,FLD-022,FLD-023,FLD-024,FLD-025,FLD-026,FLD-027">${ui.pageHeader('坐席维护','管理云呼叫坐席、服务技能和启停状态。业务账号关联请进入业务系统菜单。')}${BusinessIssues.section('坐席创建')}${filterPanel('agents','坐席姓名 / 业务系统')}${shell('agents',rows,[
    {key:'userName',label:'坐席',render:(v,r)=>`<button class="table-link" onclick="window.Pages['agent-center'].openAgent('${r.contactCenterIdentityId}')"><strong>${esc(v)}</strong><small>${esc(r.mobile||'未填写手机号')}</small></button>`},{key:'tenantId',label:'所属租户',render:v=>esc(tenantName(v))},{key:'skills',label:'服务技能'},{key:'agentStatus',label:'话务状态',render:v=>ui.status(v)},{key:'lifecycleStatus',label:'启用状态',render:v=>ui.status(v)},{key:'syncStatus',label:'配置状态',render:v=>ui.status(v)},{key:'contactCenterIdentityId',label:'操作',className:'action-column',render:(v,r)=>`<div class="table-actions"><button onclick="window.Pages['agent-center'].openAgent('${v}')">查看</button>${r.lifecycleStatus==='已启用'?`<button onclick="window.Pages['agent-center'].disable('${v}')">停用</button>`:(r.lifecycleStatus==='已停用'?`<button onclick="window.Pages['agent-center'].restore('${v}')">恢复</button>`:'')}${r.lifecycleStatus==='已删除'?'':`<button class="danger" onclick="window.Pages['agent-center'].remove('${v}')">删除</button>`}</div>`}
  ],'<button class="btn" onclick="window.Pages[\'agent-center\'].openSingle()">新增坐席</button>','云呼叫坐席独立维护；租户管理员按手机号查询已接入业务系统，确认后绑定双方账号 ID。')}</section>`;}
  function renderSkills(){const current=filters.skills,keyword=current.keyword.toLowerCase();const relations=scoped(CloudCallData.agentSkills.map(r=>{const agent=agentByIdentity(r.identityId)||{};const group=CloudCallData.physicalSkillGroups.find(g=>g.physicalGroupId===r.physicalGroupId)||{};return {...r,tenantId:agent.tenantId,instanceId:agent.instanceId,agentName:agent.userName,groupName:group.name};})).filter(row=>(!keyword||`${row.agentName} ${row.groupName}`.toLowerCase().includes(keyword))&&(current.status==='全部状态'||row.status===current.status));return `<section class="platform-page agent-skill-page" data-anno-page="agent-skills" data-anno-label="坐席多技能与等级" data-anno-kind="region" data-anno-fields="FLD-035,FLD-036,FLD-037,FLD-038,FLD-039">${ui.pageHeader('坐席技能','为坐席分配一个或多个技能；呼叫按坐席状态、路由规则与技能等级分配。')}${filterPanel('skills','坐席 / 服务技能')}${shell('skills',relations,[
    {key:'agentName',label:'坐席'},{key:'groupName',label:'服务技能'},{key:'skillLevel',label:'技能等级',help:'1 级优先，10 级最低。系统先按管理员配置选择服务技能，再在该技能内结合坐席状态和等级分配。',render:(v,r)=>`<select class="level-select" onchange="window.Pages['agent-center'].changeLevel('${r.relationId}',this.value)">${[1,2,3,4,5,6,7,8,9,10].map(x=>`<option ${x===v?'selected':''}>${x}</option>`).join('')}</select>`},{key:'status',label:'状态',render:v=>ui.status(v)},{key:'syncStatus',label:'配置状态',render:v=>ui.status(v)},{key:'relationId',label:'操作',className:'action-column',render:v=>`<div class="table-actions"><button class="danger" onclick="window.Pages['agent-center'].unassign('${v}')">移除</button></div>`}
  ],'<button class="btn btn-primary" onclick="window.Pages[\'agent-center\'].openSkillAssign()">分配坐席技能</button>','一个坐席可拥有多个服务技能；技能等级 1 最高、10 最低。')}</section>`;}
  function renderSync(){const source=scoped(CloudCallData.syncRecords),current=filters.sync,keyword=current.keyword.toLowerCase();const rows=source.filter(row=>(!keyword||`${row.objectName} ${row.objectType}`.toLowerCase().includes(keyword))&&(current.status==='全部状态'||row.status===current.status));return `<section class="platform-page sync-page" data-anno-page="sync-records" data-anno-label="逐项同步与失败重试" data-anno-kind="region" data-anno-fields="FLD-027,FLD-028,FLD-029,FLD-030,FLD-031,FLD-032,FLD-033,FLD-034">${ui.pageHeader('坐席配置记录','查看坐席配置、业务账号关联和技能调整记录。')}${filterPanel('sync','坐席 / 配置类型')}<div class="kpi-grid">${ui.kpi('今日处理',source.length,'当前租户范围')}${ui.kpi('成功',source.filter(x=>x.status==='成功').length,'仅本地配置生效')}${ui.kpi('失败',source.filter(x=>x.status==='失败').length,'可单独重试','warning')}${ui.kpi('核查中',source.filter(x=>x.status==='核查中').length,'等待资料确认')}</div>${shell('sync',rows,[
    {key:'objectName',label:'坐席 / 对象'},{key:'objectType',label:'配置类型'},{key:'status',label:'处理结果',render:v=>ui.status(v)},{key:'failureReason',label:'处理说明',render:(v,r)=>`<span class="${r.status==='失败'?'danger-text':''}">${esc(friendlyReason(v))}</span>${r.resourceCheckStatus?ui.help('仅 DEMO 资源回查：'+r.resourceCheckStatus+'；导入执行状态：'+r.executionStatus+'；真实 POC 未验证。执行编号和资源存在均不能证明厂商执行终态。'):''}`},{key:'retryCount',label:'已重试'},{key:'updatedAt',label:'更新时间'},{key:'syncId',label:'操作',className:'action-column',render:(v,r)=>['失败','核查中'].includes(r.status)?`<div class="table-actions"><button onclick="window.Pages['agent-center'].retry('${v}')">重新处理</button></div>`:'—'}
  ],'', '业务账号由管理员按手机号查询并确认关联，关联不会同步创建账号。配置与关联记录均为本地演示。')}</section>`;}
  function render(options){view=options?.view||view;if(view==='skills')return renderSkills();if(view==='sync')return renderSync();return renderAgents();}
  function mayManage(row){return AppState.get().activeDomain==='CLOUD_CONTACT_CENTER'&&AppState.canMenu('agents.manage')&&AppState.authorizeObject('',row);}
  function contextKey(){const s=AppState.get();return [s.accountId,s.sessionId,s.tenantId,s.instanceId,s.activeDomain].join('|');}
  let createContext='', retrySyncId='', createRequestId='', creating=false;
  function openSingle(syncId){
    const failed=CloudCallData.syncRecords.find(r=>r.syncId===syncId);
    if(syncId&&(!failed||!mayManage(failed)||failed.status==='成功'))return;
    retrySyncId=failed?.syncId||'';
    const tenants=scoped(CloudCallData.tenants).filter(t=>(!failed||t.tenantId===failed.tenantId)&&mayManage(t)&&t.status==='启用'&&t.capabilitySet.includes('CLOUD_CONTACT_CENTER'));
    if(!tenants.length)return;createContext=contextKey();createRequestId=crypto.randomUUID();creating=false;
    ui.openLayer('agent-single',`<div class="layer-header"><div><h2>${failed?'修改并重新提交坐席':'新增云呼叫坐席'}</h2><p>维护坐席基础资料和服务配置。</p></div><button onclick="PlatformUI.closeLayer('agent-single')">×</button></div><div class="layer-body"><div class="form-grid"><label class="field"><span>所属租户</span><select id="newAgentTenant">${tenants.map(t=>`<option value="${esc(t.tenantId)}">${esc(t.name)}</option>`).join('')}</select></label><label class="field"><span>姓名</span><input id="newAgentName" value="${esc(failed?.objectName||'')}" maxlength="40"></label><label class="field"><span>手机号</span><input id="newAgentMobile" maxlength="11" type="tel"></label><label class="field"><span>坐席登录名</span><input id="newAgentLogin" maxlength="40"></label><label class="field"><span>邮箱</span><input id="newAgentEmail" type="email"></label></div><div id="newAgentError" aria-live="polite"></div></div><div class="layer-footer"><span class="layer-footer-note">本地演示</span><button class="btn" onclick="PlatformUI.closeLayer('agent-single')">取消</button><button class="btn btn-primary" onclick="window.Pages['agent-center'].createSingle()">保存</button></div>`,'wide');
  }
  function buildAgent(input,tenant){
    const userName=String(input.userName||'').trim(),mobile=String(input.mobile||'').trim(),loginName=String(input.loginName||'').trim(),email=String(input.email||'').trim();
    let error=!userName?'请输入姓名':userName.length>40?'姓名不能超过40个字':!/^1[3-9]\d{9}$/.test(mobile)?'请输入正确的手机号':!loginName?'请输入坐席登录名':loginName.length>40?'坐席登录名不能超过40个字符':!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email.length>100?'请输入有效邮箱':'';
    if(!error&&CloudCallData.agents.some(a=>a.instanceId===tenant.instanceId&&a.lifecycleStatus!=='已删除'&&a.loginName===loginName))error='坐席登录名已存在';
    if(error)return {ok:false,message:error};
    return {ok:true,agent:{agentRecordId:CloudResourceRules.id('AGT'),contactCenterIdentityId:CloudResourceRules.id('CCI'),businessSystemId:'',businessUserId:'',accountId:'',userName,mobile,tenantId:tenant.tenantId,instanceId:tenant.instanceId,cccUserId:CloudResourceRules.id('DEMO-CCC'),ramId:CloudResourceRules.id('DEMO-RAM'),loginName,email,roleId:'Agent@'+tenant.instanceId,workMode:'ON_SITE',lifecycleStatus:'已启用',agentStatus:'离线',syncStatus:'同步成功',phonebarPermission:true,currentCall:false,acceptNewTasks:true,evidenceType:'DEMO',realVerification:'未验证'}};
  }
  async function createSingle(){
    if(creating)return;
    const value=id=>document.getElementById(id)?.value.trim()||'',tenant=CloudCallRuntime.tenant(value('newAgentTenant'));
    if(createContext!==contextKey()||!tenant||!mayManage(tenant)||tenant.status!=='启用'||!tenant.capabilitySet.includes('CLOUD_CONTACT_CENTER'))return showToast('当前权限或租户已变化，请重新打开新增页面','warning');
    const userName=value('newAgentName'),mobile=value('newAgentMobile'),loginName=value('newAgentLogin'),email=value('newAgentEmail');
    const failed=CloudCallData.syncRecords.find(r=>r.syncId===retrySyncId);
    if(retrySyncId&&(!failed||failed.status==='成功'||failed.tenantId!==tenant.tenantId||!mayManage(failed)))return;
    const submittedContext=createContext;creating=true;
    const result=await AccountSeat.create({tenantId:tenant.tenantId,userName,mobile,loginName,email},{requestId:createRequestId});
    creating=false;if(submittedContext!==contextKey())return;
    if(!result.ok){const errorNode=document.getElementById('newAgentError');if(errorNode)errorNode.innerHTML=ui.alert('warning','未能开通坐席',esc(result.message));return;}
    const agent=result.agent;
    if(failed){failed.status='成功';failed.retryCount+=1;failed.updatedAt=new Date().toLocaleString('zh-CN',{hour12:false});failed.createdIdentityId=agent.contactCenterIdentityId;const issue=CloudCallData.exceptions.find(r=>r.objectId===failed.objectId);if(issue)BusinessIssues.record(issue,'修改坐席资料后重新提交','坐席已创建（本地演示），原失败记录保留',true);retrySyncId='';}
    createContext='';ui.closeLayer('agent-single');showToast('坐席已新增，请配置技能（本地演示）','success');navigateTo('agent-maintenance');openSkillAssign(agent.contactCenterIdentityId);
  }
  function openAgent(id){const row=agentByIdentity(id);if(!row||!mayManage(row))return;const relations=CloudCallData.agentSkills.filter(x=>x.identityId===id).map(x=>{const g=CloudCallData.physicalSkillGroups.find(y=>y.physicalGroupId===x.physicalGroupId);return `${g?.name||'未命名技能'}（等级 ${x.skillLevel}）`;});const basic=`<dl class="detail-grid"><dt>姓名</dt><dd>${esc(row.userName)}</dd><dt>手机号</dt><dd>${esc(row.mobile||'—')}</dd><dt>所属租户</dt><dd>${esc(tenantName(row.tenantId))}</dd></dl>`;const work=`<dl class="detail-grid"><dt>启用状态</dt><dd>${ui.status(row.lifecycleStatus)}</dd><dt>当前话务状态</dt><dd>${ui.status(row.agentStatus)}</dd><dt>接收新任务</dt><dd>${row.acceptNewTasks?'允许':'禁止'}</dd><dt>服务技能</dt><dd>${relations.map(x=>`<span class="mini-tag">${esc(x)}</span>`).join('')||'尚未分配'}</dd></dl>${row.currentCall?ui.alert('warning','当前正在通话','停用后将立即停止分配新任务，当前通话结束后再完成停用。'):''}`;const technical=`<details class="technical-details"><summary>技术信息</summary><dl class="detail-grid"><dt>云呼叫坐席编号</dt><dd><code>${esc(row.contactCenterIdentityId)}</code></dd><dt>云平台用户编号</dt><dd><code>${esc(row.cccUserId)}</code></dd><dt>RAM 账号</dt><dd><code>${esc(row.ramId)}</code></dd><dt>开通邮箱</dt><dd>${esc(row.email||'尚未取得')}</dd><dt>角色映射</dt><dd>${esc(row.roleId)}</dd><dt>工作模式</dt><dd>${esc(row.workMode||'—')}</dd><dt>证据范围</dt><dd>仅本地演示；未取得真实开通回执</dd></dl></details>`;ui.openLayer('agent-detail',`<div class="layer-header"><div><h2>${esc(row.userName)}</h2><p>${esc(row.lifecycleStatus)} · ${esc(row.syncStatus)}</p></div><button onclick="PlatformUI.closeLayer('agent-detail')">×</button></div><div class="layer-body">${ui.detailSection('基本信息',basic)}${ui.detailSection('服务配置',work)}${AgentWorkbench.bindingPanel(row)}${technical}</div><div class="layer-footer"><button class="btn" onclick="PlatformUI.closeLayer('agent-detail')">关闭</button></div>`,'wide');}
  function disable(id,confirmed){
    const row=agentByIdentity(id);if(!row||!mayManage(row)||row.lifecycleStatus!=='已启用')return;
    if(!confirmed)return ui.confirm({id:'agent-disable',title:'停用坐席',danger:true,body:'<p>立即停止分配新任务，当前通话允许完成。</p>',confirmText:'确认停用',onConfirm(){disable(id,true);}});
    const next={...row,acceptNewTasks:false,lifecycleStatus:row.currentCall?'停用中':'已停用'};
    if(!row.currentCall){next.phonebarPermission=false;next.agentStatus='离线';}
    if(!AccountSeat.persistAgent(next))return;Object.assign(row,next);
    showToast(row.currentCall?'已禁止新任务；当前通话结束后完成停用':'坐席已停用',row.currentCall?'warning':'success');
    CloudResourceRules.recount();CloudResourceRules.changed(row.tenantId);CloudCallRuntime.addAudit('停用坐席',id,row.tenantId,'已启用',row.lifecycleStatus);navigateTo('agent-maintenance');
  }
  function restore(id){const row=agentByIdentity(id);if(!row||!mayManage(row)||row.lifecycleStatus!=='已停用')return;const next={...row,lifecycleStatus:'已启用',acceptNewTasks:true,phonebarPermission:true,syncStatus:'同步成功'};if(!AccountSeat.persistAgent(next))return;Object.assign(row,next);CloudResourceRules.recount();CloudResourceRules.changed(row.tenantId);showToast('坐席已按新状态恢复启用','success');navigateTo('agent-maintenance');}
  function remove(id){
    const row=agentByIdentity(id);if(!row||!mayManage(row)||row.lifecycleStatus==='已删除')return;
    if(AccountSeat.inUse(row)){showToast('请先结束通话、完成话后处理并下线，再删除坐席','warning');return;}
    const context=contextKey();ui.confirm({id:'agent-delete-confirm',title:'删除坐席',danger:true,confirmText:'确认删除',body:`<p>删除后不恢复历史配置；再次开通将按新坐席创建。通话与操作历史永久保留。</p><p><code>${esc(id)}</code></p>`,onConfirm(){
      if(context!==contextKey()||!mayManage(row)||AccountSeat.inUse(row))return showToast('当前权限或坐席使用状态已变化，请重新核对','warning');
      const next={...row,lifecycleStatus:'已删除',agentStatus:'离线',acceptNewTasks:false,phonebarPermission:false};
      if(!AccountSeat.persistAgent(next,[]))return;Object.assign(row,next);CloudResourceRules.recount();CloudResourceRules.changed(row.tenantId);showToast('坐席已删除，历史记录仍保留','success');navigateTo('agent-maintenance');
    }});
  }
  let skillAssignContext='';
  function openSkillAssign(identityId){
    const agents=scoped(CloudCallData.agents).filter(x=>mayManage(x)&&x.lifecycleStatus==='已启用');
    const selected=identityId?agents.find(a=>a.contactCenterIdentityId===identityId):agents[0];if(!selected)return showToast('暂无可配置技能的启用坐席','warning');
    const groups=scoped(CloudCallData.physicalSkillGroups).filter(g=>g.status==='已启用'&&g.tenantId===selected.tenantId&&g.instanceId===selected.instanceId);skillAssignContext=contextKey();
    ui.openLayer('skill-assign',`<div class="layer-header"><div><h2>分配坐席技能</h2><p>一个坐席可分配多个服务技能</p></div><button onclick="PlatformUI.closeLayer('skill-assign')">×</button></div><div class="layer-body"><div class="form-grid"><label class="field"><span>坐席</span><select id="assignAgent" onchange="window.Pages['agent-center'].filterAssignGroups()">${agents.map(x=>`<option value="${x.contactCenterIdentityId}" ${x===selected?'selected':''}>${esc(x.userName)}</option>`).join('')}</select></label><label class="field"><span>服务技能</span><select id="assignGroup">${groups.map(x=>`<option value="${x.physicalGroupId}">${esc(x.name)}</option>`).join('')||'<option value="">该租户暂无已启用服务技能</option>'}</select></label><label class="field"><span>技能等级</span><select id="assignLevel">${[1,2,3,4,5,6,7,8,9,10].map(x=>`<option>${x}</option>`).join('')}</select><small class="field-hint">1 级最高，10 级最低。</small></label></div></div><div class="layer-footer"><button class="btn" onclick="PlatformUI.closeLayer('skill-assign')">取消</button><button class="btn btn-primary" onclick="window.Pages['agent-center'].saveSkill()">保存</button></div>`,'small');
  }
  function saveSkill(){
    const identityId=document.getElementById('assignAgent')?.value,physicalGroupId=document.getElementById('assignGroup')?.value,skillLevel=Number(document.getElementById('assignLevel')?.value);
    const agent=agentByIdentity(identityId),group=CloudCallData.physicalSkillGroups.find(g=>g.physicalGroupId===physicalGroupId);
    if(skillAssignContext!==contextKey()||!agent||!mayManage(agent)||!group||agent.tenantId!==group.tenantId||agent.instanceId!==group.instanceId||group.status!=='已启用'||agent.lifecycleStatus!=='已启用'||!Number.isInteger(skillLevel)||skillLevel<1||skillLevel>10)return CloudResourceRules.error('skill-assign','请核对坐席、同租户服务技能和技能等级');
    const relations=CloudCallData.agentSkills.filter(x=>x.identityId===identityId).map(x=>({...x})),existing=relations.find(x=>x.physicalGroupId===physicalGroupId);
    if(existing){existing.skillLevel=skillLevel;existing.syncStatus='同步成功';}else relations.push({relationId:CloudCallRuntime.sequence('AS',CloudCallData.agentSkills),identityId,physicalGroupId,skillLevel,status:'已生效',syncStatus:'同步成功'});
    if(!AccountSeat.persistAgent(agent,relations))return;CloudResourceRules.recount();CloudResourceRules.changed(agent.tenantId);ui.closeLayer('skill-assign');showToast('坐席技能已保存（本地演示）','success');navigateTo('agent-skills');
  }
  function changeLevel(id,value){const row=CloudCallData.agentSkills.find(x=>x.relationId===id),agent=row&&agentByIdentity(row.identityId),level=Number(value);if(!agent||!mayManage(agent)||!Number.isInteger(level)||level<1||level>10)return;const relations=CloudCallData.agentSkills.filter(x=>x.identityId===row.identityId).map(x=>x===row?{...x,skillLevel:level,syncStatus:'同步成功'}:{...x});if(!AccountSeat.persistAgent(agent,relations))return;showToast(`技能等级已调整为 ${level}`,'success');}
  function unassign(id,confirmed){const row=CloudCallData.agentSkills.find(r=>r.relationId===id),agent=row&&agentByIdentity(row.identityId);if(!row||!agent||!mayManage(agent))return;if(!confirmed)return ui.confirm({id:'skill-remove',title:'移除坐席技能',danger:true,body:'<p>移除后，该坐席将不再接收此技能的新呼叫。</p>',confirmText:'确认移除',onConfirm(){unassign(id,true);}});if(!AccountSeat.persistAgent(agent,CloudCallData.agentSkills.filter(r=>r.identityId===row.identityId&&r.relationId!==id)))return;CloudResourceRules.recount();CloudResourceRules.changed(agent.tenantId);showToast('坐席技能已移除','success');navigateTo('agent-skills');}
  function retry(id){const row=CloudCallData.syncRecords.find(x=>x.syncId===id);if(!row||!mayManage(row))return;const issue=CloudCallData.exceptions.find(x=>x.objectId===row.objectId);if(issue)return BusinessIssues.open(issue.exceptionId);showToast('请在对应的配置页面查看原因并修改，原记录已保留','info');}

  function filterAssignGroups(){
    const agent=agentByIdentity(document.getElementById('assignAgent').value);
    document.getElementById('assignGroup').innerHTML=scoped(CloudCallData.physicalSkillGroups).filter(g=>g.tenantId===agent?.tenantId&&g.instanceId===agent?.instanceId&&g.status==='已启用').map(g=>'<option value="'+g.physicalGroupId+'">'+esc(g.name)+'</option>').join('')||'<option value="">该租户暂无已启用服务团队</option>';
  }
  function routeFor(key){return key==='skills'?'agent-skills':key==='sync'?'sync-records':'agent-maintenance';}
  function query(key){filters[key].keyword=document.getElementById(`${key}Keyword`)?.value||'';filters[key].status=document.getElementById(`${key}Status`)?.value||'全部状态';pages[key]=1;navigateTo(routeFor(key));}
  function resetFilters(key){filters[key]={keyword:'',status:'全部状态'};pages[key]=1;navigateTo(routeFor(key));}
  function setPage(key,value){pages[key]=Math.max(1,Number(value)||1);navigateTo(routeFor(key));}
  function refresh(key){showToast('数据已刷新','success');navigateTo(routeFor(key));}
  window.Pages=window.Pages||{};window.Pages['agent-center']={render,init(){},openSingle,createSingle,buildAgent,filterAssignGroups,openAgent,disable,restore,remove,openSkillAssign,saveSkill,changeLevel,unassign,retry,query,resetFilters,setPage,refresh};
})();
