/** 云呼叫五类报表：呼叫、外呼任务、呼入、坐席、技能组。 */
(function(){
  'use strict';const ui=PlatformUI,esc=ui.escape;let view='overview';const filters={};function currentFilter(){return filters[view]||(filters[view]={period:'近 7 日',tenantId:'',keyword:''});}
  function scoped(rows,ignoreKeyword){
    const f=currentFilter(),now=new Date(),start=new Date(now.getFullYear(),now.getMonth(),now.getDate()),end=new Date(start);end.setDate(end.getDate()+1);
    if(f.period==='近 7 日')start.setDate(start.getDate()-6);if(f.period==='本月')start.setDate(1);
    return AppState.scoped(rows||[]).filter(r=>{
      if(f.tenantId&&r.tenantId!==f.tenantId)return false;
      const raw=r.endedAt||r.answeredAt||r.ringingAt||r.scheduleAt||r.createdAt;const date=Date.parse(raw);
      if(raw&&Number.isFinite(date)&&(date<start.getTime()||date>=end.getTime()))return false;
      if(!f.keyword||ignoreKeyword)return true;
      const group=CloudCallData.physicalSkillGroups.find(g=>g.skillGroupId===r.skillGroupId),task=CloudCallData.tasks.find(t=>t.taskId===r.taskId);
      return [r.name,r.userName,r.agentName,r.callType,r.caller,r.callee,group?.name,task?.name].join(' ').includes(f.keyword);
    });
  }
  function pct(a,b){return b?`${(a/b*100).toFixed(1)}%`:'0.0%';}
  function reportHeader(title,desc){const f=currentFilter(),tenants=AppState.isSuper()?AppState.availableTenants():[AppState.currentTenant()];return ui.pageHeader(title,desc)+'<div class="filter-panel"><label class="field"><span>统计周期</span><select id="reportPeriod">'+['今日','近 7 日','本月'].map(t=>'<option '+(t===f.period?'selected':'')+'>'+t+'</option>').join('')+'</select></label><label class="field"><span>业务租户</span><select id="reportTenant"><option value="">当前权限范围</option>'+tenants.filter(Boolean).map(t=>'<option value="'+t.tenantId+'" '+(f.tenantId===t.tenantId?'selected':'')+'>'+esc(t.name)+'</option>').join('')+'</select></label><label class="field grow"><span>关键词</span><input id="reportKeyword" value="'+esc(f.keyword)+'" placeholder="任务、坐席或服务技能"></label><div class="filter-actions"><button class="btn" onclick="window.Pages[\'report-center\'].reset()">重置</button><button class="btn btn-primary" onclick="window.Pages[\'report-center\'].query()">查询</button></div></div>'+ui.toolbar('','<button class="btn" onclick="doExport(event)">导出报表</button>'+ui.help('指标、图表和明细按同一周期、租户和关键词统计。智能外呼继续使用原有报表。'));}
  function bars(rows,field){
    const f=currentFilter(),now=new Date(),start=new Date(now.getFullYear(),now.getMonth(),now.getDate());if(f.period==='近 7 日')start.setDate(start.getDate()-6);if(f.period==='本月')start.setDate(1);
    const items=[];for(let day=new Date(start);day<=now;day.setDate(day.getDate()+1)){const key=day.toLocaleDateString('sv-SE');items.push({label:(day.getMonth()+1)+'/'+day.getDate(),count:rows.filter(r=>String(r.endedAt||r.answeredAt||r.ringingAt||r.scheduleAt||r.createdAt||'').slice(0,10)===key).reduce((n,r)=>n+(field?Number(r[field]||0):1),0)});}
    const max=Math.max(1,...items.map(x=>x.count));return '<div class="bar-chart report-bars">'+items.map(x=>'<div title="'+x.label+'：'+x.count+'"><span style="height:'+x.count/max*100+'%"></span><small>'+x.label+'</small></div>').join('')+'</div>';
  }
  function queueAverage(calls){const values=calls.map(c=>{const start=Date.parse(c.queueAt),end=Date.parse(c.answeredAt);return Number.isFinite(start)&&Number.isFinite(end)&&end>=start?(end-start)/1000:null;}).filter(x=>x!==null);return values.length?Math.round(values.reduce((a,b)=>a+b,0)/values.length)+' 秒':'—';}
  function query(){filters[view]={period:document.getElementById('reportPeriod').value,tenantId:document.getElementById('reportTenant').value,keyword:document.getElementById('reportKeyword').value.trim()};navigateTo(location.hash.slice(1));}
  function reset(){delete filters[view];navigateTo(location.hash.slice(1));}

  function overview(){const calls=scoped(CloudCallData.calls);const connected=calls.filter(x=>['接通','完成'].includes(x.result)).length;const applicable=calls.filter(x=>!x.simulation&&x.recordingApplicability!=='NOT_APPLICABLE_PURE_IVR'&&x.recordingApplicability!=='待判定');const available=applicable.filter(x=>x.recordingStatus==='可播放').length;const rows=['人工外呼','预外呼','IVR 外呼','呼入'].map(type=>{const list=calls.filter(x=>x.callType===type);return {type,total:list.length,connected:list.filter(x=>['接通','完成'].includes(x.result)).length,rate:pct(list.filter(x=>['接通','完成'].includes(x.result)).length,list.length),duration:list.reduce((n,x)=>n+x.durationSeconds,0),recording:list.filter(x=>x.recordingStatus==='可播放').length};});return `<section class="platform-page report-page" data-anno-page="cloud-overview-report" data-anno-label="云呼叫总览与录音覆盖率" data-anno-kind="chart" data-anno-fields="FLD-095,FLD-096,FLD-097,FLD-098,FLD-099">${reportHeader('呼叫总览','汇总人工外呼、预外呼、IVR 外呼和呼入，不包含智能外呼。')}<div class="kpi-grid">${ui.kpi('呼叫量',calls.length,'当前租户与实例')}${ui.kpi('有效接通',connected,`接通率 ${pct(connected,calls.length)}`)}${ui.kpi('通话时长',`${calls.reduce((n,x)=>n+x.durationSeconds,0)} 秒`,'含有人参与阶段')}${ui.kpi('录音覆盖率',pct(available,applicable.length),`${available}/${applicable.length}；排除纯 IVR 与演示通话`)}</div>${ui.alert('info','录音覆盖率分母规则',`适用记录 ${applicable.length} 条；纯 IVR 无人参与记录标记 NOT_APPLICABLE_PURE_IVR，不进入分子和分母。`)}<div class="content-grid"><article class="panel-card span-7"><div class="panel-header"><div><h2>所选周期呼叫趋势</h2><p>来源：RocketMQ 话务事件 + CDR 校准</p></div></div><div class="panel-body">${bars(calls)}</div></article><article class="panel-card span-5"><div class="panel-header"><div><h2>类型结构</h2><p>当前范围</p></div></div><div class="panel-body metric-list">${rows.map((x,i)=>`<div class="metric-row"><span>${esc(x.type)}</span><div class="metric-bar"><i style="width:${calls.length?x.total/calls.length*100:0}%"></i></div><strong>${x.total}</strong></div>`).join('')}</div></article><article class="span-12">${ui.table([{key:'type',label:'业务类型'},{key:'total',label:'呼叫量'},{key:'connected',label:'有效接通'},{key:'rate',label:'接通率'},{key:'duration',label:'通话秒数'},{key:'recording',label:'可用录音'}],rows)}</article></div></section>`;}
  function outbound(){const tasks=scoped(CloudCallData.tasks);const rows=tasks.map(x=>({...x,plan:CloudCallData.callPlans.find(p=>p.callPlanId===x.planId)?.name||x.executionConfig?.name||'历史配置',finishRate:pct(x.completed,x.total),connectRate:pct(x.connected,x.completed)}));return `<section class="platform-page report-page">${reportHeader('外呼任务报表','分析预外呼和 IVR 外呼任务的执行规模、完成率、接通率与配置版本。')}<div class="kpi-grid">${ui.kpi('任务数',tasks.length,'预外呼 + IVR')}${ui.kpi('名单量',tasks.reduce((n,x)=>n+x.total,0),'当前统计周期')}${ui.kpi('已完成',tasks.reduce((n,x)=>n+x.completed,0),'终态记录')}${ui.kpi('有效接通',tasks.reduce((n,x)=>n+x.connected,0),'按任务结果')}</div><div class="content-grid"><article class="panel-card span-7"><div class="panel-header"><div><h2>执行任务完成量</h2><p>来源：任务快照与 Campaign 结果</p></div></div><div class="panel-body">${bars(tasks,'completed')}</div></article><article class="panel-card span-5"><div class="panel-header"><div><h2>任务类型分布</h2><p>预外呼与 IVR 分开统计</p></div></div><div class="panel-body metric-list"><div class="metric-row"><span>预外呼</span><div class="metric-bar"><i style="width:${tasks.length?tasks.filter(x=>x.callType==='预外呼').length/tasks.length*100:0}%"></i></div><strong>${tasks.filter(x=>x.callType==='预外呼').length}</strong></div><div class="metric-row"><span>IVR 外呼</span><div class="metric-bar"><i style="width:${tasks.length?tasks.filter(x=>x.callType==='IVR 外呼').length/tasks.length*100:0}%"></i></div><strong>${tasks.filter(x=>x.callType==='IVR 外呼').length}</strong></div></div></article><article class="span-12">${ui.table([{key:'name',label:'任务'},{key:'callType',label:'类型'},{key:'plan',label:'执行配置'},{key:'total',label:'名单量'},{key:'completed',label:'完成量'},{key:'finishRate',label:'完成率'},{key:'connected',label:'接通量'},{key:'connectRate',label:'接通率'},{key:'status',label:'状态',render:v=>ui.status(v)}],rows)}</article></div></section>`;}
  function inbound(){const calls=scoped(CloudCallData.calls.filter(x=>x.callType==='呼入'));const rows=calls.map(x=>({id:x.callId,tenant:CloudCallRuntime.tenant(x.tenantId)?.name||x.tenantId,route:CloudCallData.tenants.reduce((text,t)=>text.split(t.tenantId).join(t.name),x.routeEvidence||'—'),queue:x.queueAt,agent:x.agentName||'未接通',result:x.result,duration:x.durationSeconds}));return `<section class="platform-page report-page">${reportHeader('呼入服务报表','分析 IVR 分流、排队、人工接通和超时结果；不提供实时墙板。')}<div class="kpi-grid">${ui.kpi('呼入量',calls.length,'客户主动来电')}${ui.kpi('人工接通',calls.filter(x=>x.result==='接通').length,`接通率 ${pct(calls.filter(x=>x.result==='接通').length,calls.length)}`)}${ui.kpi('平均排队',queueAverage(calls),'按事件时间计算')}${ui.kpi('排队超时',calls.filter(x=>x.result==='排队超时').length,'超时提示后挂断')}</div><div class="content-grid"><article class="panel-card span-7"><div class="panel-header"><div><h2>所选周期呼入趋势</h2><p>来源：通话事件与呼入路由版本</p></div></div><div class="panel-body">${bars(calls)}</div></article><article class="panel-card span-5"><div class="panel-header"><div><h2>结果分布</h2><p>接通 / 排队超时</p></div></div><div class="panel-body metric-list"><div class="metric-row"><span>人工接通</span><div class="metric-bar"><i style="width:${calls.length?calls.filter(x=>x.result==='接通').length/calls.length*100:0}%"></i></div><strong>${calls.filter(x=>x.result==='接通').length}</strong></div><div class="metric-row"><span>排队超时</span><div class="metric-bar"><i style="width:${calls.length?calls.filter(x=>x.result==='排队超时').length/calls.length*100:0}%"></i></div><strong>${calls.filter(x=>x.result==='排队超时').length}</strong></div></div></article><article class="span-12">${ui.table([{key:'id',label:'通话编号'},{key:'tenant',label:'锁定租户'},{key:'route',label:'路由证据'},{key:'queue',label:'入队时间'},{key:'agent',label:'接听坐席'},{key:'result',label:'结果',render:v=>ui.status(v)},{key:'duration',label:'通话秒数'}],rows)}</article></div></section>`;}
  function agents(){const rows=scoped(CloudCallData.agents).map(a=>{const calls=scoped(CloudCallData.calls.filter(x=>x.agentIdentityId===a.contactCenterIdentityId),true);return {name:a.userName,tenant:CloudCallRuntime.tenant(a.tenantId)?.name||a.tenantId,skills:CloudCallData.agentSkills.filter(x=>x.identityId===a.contactCenterIdentityId).length,calls:calls.length,connected:calls.filter(x=>x.result==='接通').length,talk:calls.reduce((n,x)=>n+x.durationSeconds,0),status:a.lifecycleStatus};});return `<section class="platform-page report-page">${reportHeader('坐席报表','查看坐席承接量、接通量、通话时长和服务技能覆盖。')}<div class="kpi-grid">${ui.kpi('坐席数',rows.length,'当前租户范围')}${ui.kpi('已启用',rows.filter(x=>x.status==='已启用').length,'当前可接听')}${ui.kpi('承接通话',rows.reduce((n,x)=>n+x.calls,0),'有人参与记录')}${ui.kpi('通话时长',`${rows.reduce((n,x)=>n+x.talk,0)} 秒`,'纯 IVR 不计坐席')}</div><article>${ui.table([{key:'name',label:'坐席'},{key:'tenant',label:'租户'},{key:'skills',label:'服务技能数'},{key:'calls',label:'承接量'},{key:'connected',label:'接通量'},{key:'talk',label:'通话秒数'},{key:'status',label:'状态',render:v=>ui.status(v)}],rows)}</article></section>`;}
  function skills(){const rows=scoped(CloudCallData.physicalSkillGroups).map(g=>{const calls=scoped(CloudCallData.calls.filter(x=>x.skillGroupId===g.skillGroupId),true);return {name:g.name,tenant:CloudCallRuntime.tenant(g.tenantId)?.name||g.tenantId,members:CloudResourceRules.members(g).length,calls:calls.length,connected:calls.filter(x=>x.result==='接通').length,rate:pct(calls.filter(x=>x.result==='接通').length,calls.length),queue:queueAverage(calls),status:g.status};});return `<section class="platform-page report-page">${reportHeader('服务技能报表','按租户服务技能查看承接量、接通率、排队时长和坐席规模。')}<div class="kpi-grid">${ui.kpi('服务技能',rows.length,'按租户独立维护')}${ui.kpi('坐席成员',rows.reduce((n,x)=>n+x.members,0),'允许一人多技能')}${ui.kpi('承接通话',rows.reduce((n,x)=>n+x.calls,0),'按服务技能统计')}${ui.kpi('平均排队',queueAverage(scoped(CloudCallData.calls)),'按通话记录统计')}</div><article>${ui.table([{key:'name',label:'服务技能'},{key:'tenant',label:'所属租户'},{key:'members',label:'坐席数'},{key:'calls',label:'承接量'},{key:'connected',label:'接通量'},{key:'rate',label:'接通率'},{key:'queue',label:'平均排队'},{key:'status',label:'状态',render:v=>ui.status(v)}],rows)}</article></section>`;}
  const annotationContracts={
    overview:'<section data-anno-page="cloud-overview-report" data-anno-label="云呼叫总览与录音覆盖率" data-anno-kind="region" data-anno-fields="FLD-095,FLD-096,FLD-097,FLD-098,FLD-099">',
    outbound:'<section data-anno-page="cloud-outbound-report" data-anno-label="外呼任务报表" data-anno-kind="region" data-anno-fields="FLD-095,FLD-096,FLD-097">',
    inbound:'<section data-anno-page="cloud-inbound-report" data-anno-label="呼入服务报表" data-anno-kind="region" data-anno-fields="FLD-095,FLD-096,FLD-097">',
    agents:'<section data-anno-page="cloud-agent-report" data-anno-label="坐席报表" data-anno-kind="region" data-anno-fields="FLD-019,FLD-020,FLD-027,FLD-095,FLD-096,FLD-097,FLD-099">',
    skills:'<section data-anno-page="cloud-skill-report" data-anno-label="技能组报表" data-anno-kind="region" data-anno-fields="FLD-035,FLD-036,FLD-037,FLD-095,FLD-096,FLD-097,FLD-099">'
  };
  function annotate(html,key){const attributes=annotationContracts[key].slice('<section'.length,-1).trim();return html.replace(/^<section class="platform-page report-page"[^>]*>/,`<section class="platform-page report-page" ${attributes}>`);}
  function businessCopy(html){html=html.replaceAll('RocketMQ 话务事件 + CDR 校准','通话记录与最终结果').replaceAll('任务快照与 Campaign 结果','任务执行结果').replaceAll('NOT_APPLICABLE_PURE_IVR','不适用').replaceAll('按联络中心身份分析','分析').replaceAll('联络中心身份','云呼叫坐席账号').replaceAll('物理技能组','服务技能组').replaceAll('按 SkillGroupId','按服务技能').replaceAll('阿里 SkillGroupId','技能编号').replaceAll('唯一租户','所属租户').replaceAll('实例','客户 / 品牌');return html.replace(/<div class="platform-alert info"><div><strong>录音覆盖率分母规则<\/strong><p>[\s\S]*?<\/p><\/div><\/div>/,`<div class="business-help-line"><span>录音统计口径</span>${ui.help('纯自动语音和本地演示通话不提供录音，不计入录音覆盖率；只有适用录音的通话参与计算。')}</div>`);}
  function render(options){view=options?.view||view;if(currentFilter().tenantId&&!AppState.availableTenants().some(t=>t.tenantId===currentFilter().tenantId))currentFilter().tenantId='';if(view==='outbound')return businessCopy(annotate(outbound(),'outbound'));if(view==='inbound')return businessCopy(annotate(inbound(),'inbound'));if(view==='agents')return businessCopy(annotate(agents(),'agents'));if(view==='skills')return businessCopy(annotate(skills(),'skills'));return businessCopy(annotate(overview(),'overview'));}
  window.Pages=window.Pages||{};window.Pages['report-center']={render,init(){},query,reset};
})();
